Repository MervinPraison/PraisonAI, pull requests merged in 2025-06, with the labels that each got.

#577 Add arxiv agent notebook example to cookbooks
  examples/cookbooks/arXiv_agent_notebook.ipynb
Labels: Review effort 1/5

#581 feat: Add domain context solution using existing features
  examples/python/usecases/README-domain-context.md
  examples/python/usecases/domain-context-solution.py
Labels: Review effort 3/5

#586 refactor: streamline test functions in test_scheduler.py
  .github/workflows/python-package.yml
  .github/workflows/test-comprehensive.yml
  .github/workflows/test-core.yml
  .github/workflows/test-extended.yml
  .github/workflows/test-real.yml
  .github/workflows/unittest.yml
  src/praisonai-agents/praisonaiagents/memory/__init__.py
  src/praisonai/tests/unit/test_approval_agent_integration.py
  src/praisonai/tests/unit/test_approval_basic.py
  src/praisonai/tests/unit/test_approval_interactive.py
  src/praisonai/tests/unit/test_decorator_enforcement.py
  src/praisonai/tests/unit/test_decorator_simple.py
  src/praisonai/tests/unit/test_graph_memory.py
  src/praisonai/tests/unit/test_ollama_fix.py
  src/praisonai/tests/unit/test_scheduler.py
Labels: Review effort 2/5

#592 Updated docker/docker-compose.dev.yml to fix security vulnerability [yaml.docker-compose.security.no-new-privileges.no-new-privileges]
  docker/docker-compose.dev.yml
Labels: Review effort 1/5

#594 Fix redundant tool invocation
  src/praisonai-agents/praisonaiagents/agent/agent.py
Labels: Review effort 2/5, codex

#596 Add MCP SSE tooling example
  src/praisonai-ts/examples/README-tool-examples.md
  src/praisonai-ts/examples/tools/mcp-sse.ts
  src/praisonai-ts/package.json
  src/praisonai-ts/src/tools/index.ts
  src/praisonai-ts/src/tools/mcpSse.ts
Labels: Review effort 2/5, codex

#600 Add code analysis agent notebook
  examples/cookbooks/Code_Analysis_Agent.ipynb
Labels: Review effort 2/5

#599 Update test workflow to use custom test runner for 'fast' pattern and…
  .github/workflows/python-package.yml
  src/praisonai-agents/.cursorrules
  src/praisonai-agents/CLAUDE.md
  src/praisonai-agents/agent_guardrails_example.py
  src/praisonai-agents/guardrails_example.py
  src/praisonai-agents/praisonaiagents/__init__.py
  src/praisonai-agents/praisonaiagents/agent/agent.py
  src/praisonai-agents/praisonaiagents/guardrails/__init__.py
  src/praisonai-agents/praisonaiagents/guardrails/guardrail_result.py
  src/praisonai-agents/praisonaiagents/guardrails/llm_guardrail.py
  src/praisonai-agents/praisonaiagents/task/task.py
  src/praisonai-agents/sequence.py
  src/praisonai-agents/simple_guardrail_test.py
  src/praisonai-agents/test_agent_guardrails.py
  src/praisonai-agents/test_guardrails.py
  src/praisonai-agents/tests/guardrails_example.py
Labels: Review effort 3/5

#610 fix: resolve Memory import error with litellm compatibility
  src/praisonai-agents/praisonaiagents/__init__.py
  src/praisonai-agents/praisonaiagents/memory/memory.py
  src/praisonai/tests/unit/test_comprehensive_import.py
  src/praisonai/tests/unit/test_memory_import.py
  src/praisonai/tests/unit/test_session_import.py
Labels: Review effort 2/5

#613 fix: prevent duplicate Task and Response display when using litellm with memory
  src/praisonai-agents/praisonaiagents/agent/agent.py
  src/praisonai-agents/praisonaiagents/llm/llm.py
Labels: Review effort 2/5

#622 Add Groq Llama3-8b-8192 Agent notebook
  examples/cookbooks/Groq_LPU_Powered_AI_Assistant.ipynb
Labels: Review effort 2/5

#631 feat: add remote agent connectivity with Google ADK-like API
  examples/python/remote/README.md
  examples/python/remote/remote_agent_example.py
  examples/python/remote/remote_agent_server.py
  src/praisonai-agents/praisonaiagents/session.py
  src/praisonai/tests/unit/test_remote_agent.py
Labels: Review effort 4/5

#639 Update agents.py to work with newer chainlit versions
  src/praisonai/praisonai/ui/agents.py
Labels: Review effort 2/5

#641 Allow to configure reflection prompt
  src/praisonai-agents/praisonaiagents/agent/agent.py
Labels: Review effort 2/5

#635 feat: Refactor Claude Code integration to use PraisonAI Agents
  CLAUDE_CODE_INTEGRATION_PRAISONAI_AGENTS.md
  src/praisonai/praisonai/cli.py
  src/praisonai/praisonai/ui/code.py
  src/praisonai/tests/unit/test_claude_code_integration.py
Labels: Review effort 4/5, Possible security concern
