Repository MervinPraison/PraisonAI, pull requests merged in 2025-07, with the labels that each got.

#732 Add Ai Enrollment Counselor Notebook
  examples/cookbooks/AI_Enrollment_Counselor.ipynb
  examples/cookbooks/ai_documentation_processor.ipynb
  examples/cookbooks/ai_ecommerce_shopping_assistant.ipynb
  examples/cookbooks/ai_job_hunting_assistant.ipynb
  examples/cookbooks/intelligent_programming_agent.ipynb
  examples/cookbooks/multi_agent_production_system.ipynb
  examples/cookbooks/semantic_social_network_agent_system.ipynb
  examples/cookbooks/universal_desktop_agents.ipynb
  examples/cookbooks/work_email_agent.ipynb
  examples/cookbooks/youtube_content_integrity_analyzer.ipynb
Labels: Review effort 3/5, Possible security concern

#736 feat: Add minimal latency tracking as custom tool for MCP servers
  examples/python/custom_tools/README_LATENCY_TRACKING.md
  examples/python/custom_tools/example_latency_tracking.py
  examples/python/custom_tools/latency_tracker_tool.py
  examples/python/custom_tools/mcp_server_latency_example.py
  examples/python/custom_tools/minimal_latency_example.py
  examples/python/custom_tools/tools_with_latency.py
Labels: Review effort 3/5, Possible security concern

#743 feat: implement provider pattern for lightweight/heavy LLM support
  src/praisonai-agents/praisonaiagents/agent/agent.py
  src/praisonai-agents/praisonaiagents/llm/llm.py
  src/praisonai-agents/praisonaiagents/llm/providers/__init__.py
  src/praisonai-agents/praisonaiagents/llm/providers/base.py
  src/praisonai-agents/praisonaiagents/llm/providers/factory.py
  src/praisonai-agents/praisonaiagents/llm/providers/litellm_provider.py
  src/praisonai-agents/praisonaiagents/llm/providers/openai_provider.py
  src/praisonai-agents/praisonaiagents/main.py
  src/praisonai/tests/unit/test_multi_agent_workflow.py
  src/praisonai/tests/unit/test_parallel_provider_pattern.py
  src/praisonai/tests/unit/test_provider_pattern.py
Labels: Review effort 4/5

#755 Add AI Market & Startup Trend Agent Notebook
  examples/cookbooks/AI_Enrollment_Counselor.ipynb
  examples/cookbooks/Ai_Market_Startup_Trend_Agent.ipynb
  examples/cookbooks/ai_data_analysis_agent.ipynb
  examples/cookbooks/ai_health_fitness_agent.ipynb
  examples/cookbooks/ai_market_startup_trend_agent.ipynb
  examples/cookbooks/ai_meme_creator_agent.ipynb
  examples/cookbooks/intelligent_travel_planning_agent.ipynb
  examples/cookbooks/local_rag_document_qa_agent.ipynb
Labels: Review effort 4/5, Possible security concern

#761 refactor: Phase 2 - Extract shared _build_messages helper
  src/praisonai-agents/praisonaiagents/llm/llm.py
  src/praisonai/tests/test_phase2_refactor.py
Labels: Review effort 3/5

#771 refactor: make openai_client.py self-contained like llm.py
  src/praisonai-agents/praisonaiagents/agent/agent.py
  src/praisonai-agents/praisonaiagents/llm/__init__.py
  src/praisonai-agents/praisonaiagents/llm/openai_client.py
  src/praisonai/tests/unit/test_openai_refactor_2.py
Labels: Review effort 4/5

#773 fix: comprehensive array schema validation for MCP tools
  src/praisonai-agents/praisonaiagents/llm/openai_client.py
Labels: Review effort 3/5

#774 fix: add array schema validation to llm.py for MCP tools compatibility
  src/praisonai-agents/praisonaiagents/llm/llm.py
Labels: Review effort 3/5

#775 Add Air Quality Analysis Agent Notebook to Health Fitness Agents
  examples/cookbooks/Health_Fitness_Agents/Air_Quality_Analysis_Agent.ipynb
Labels: Review effort 2/5, Possible security concern

#778 Add Game Playing Agent (Tic Tac Toe) Notebook to Programming Code Analysis Agents Folder
  examples/cookbooks/Programming_Code_Analysis_Agents/Game_Playing_Agent_Tic_Tac_Toe.ipynb
Labels: Review effort 2/5

#780 Add 5 domain-specific AI agent examples to exa-tool directory
  examples/python/tools/exa-tool/Finance_Market_Job_Agents/Financial_Coaching_Agent.py
  examples/python/tools/exa-tool/Health_Fitness_Agents/Air_Quality_Analysis_Agent.py
  examples/python/tools/exa-tool/Programming_Code_Analysis_Agents/Game_Playing_Agent_Tic_Tac_Toe.py
  examples/python/tools/exa-tool/Research_Knowledge_QA_Agents/Domain_Deep_Research_Agent.py
  examples/python/tools/exa-tool/SocialMedia_Content_Agents/News_And_Podcast_Aggregator_Agent.py
Labels: Review effort 3/5

#779 Add Domain Deep Research Agent Notebook to Research Knowledge QA Agents Folder
  examples/cookbooks/Research_Knowledge_QA_Agents/Domain_Deep_Research_Agent.ipynb
Labels: Review effort 2/5

#785 fix: remove OPENAI_API_KEY requirement for non-OpenAI providers
  src/praisonai-agents/praisonaiagents/agent/agent.py
  src/praisonai-agents/praisonaiagents/agents/agents.py
  src/praisonai-agents/praisonaiagents/agents/autoagents.py
  src/praisonai-agents/praisonaiagents/main.py
  src/praisonai-agents/praisonaiagents/process/process.py
  src/praisonai/tests/unit/test_xai_fix.py
Labels: Review effort 2/5

#783 refactor: extract Ollama handler to eliminate code duplication
  src/praisonai-agents/praisonaiagents/llm/llm.py
Labels: Review effort 3/5

#791 fix: add multi-provider support for AutoAgents
  src/praisonai-agents/praisonaiagents/agents/autoagents.py
Labels: Review effort 3/5

#789 fix: prevent double output when using litellm models
  src/praisonai-agents/praisonaiagents/agent/agent.py
Labels: Review effort 2/5

#794 PR #791: Changes from Claude
  src/praisonai-agents/praisonaiagents/agents/autoagents.py
Labels: Review effort 3/5

#781 refactor: eliminate sync/async duplication in llm.py
  src/praisonai-agents/praisonaiagents/llm/llm.py
Labels: Review effort 4/5

#801 fix: update AutoAgents prompt to generate proper TaskConfig objects
  src/praisonai-agents/praisonaiagents/agents/autoagents.py
  src/praisonai/tests/unit/test_autoagents.py
Labels: Review effort 2/5

#803 fix: replace prefix-based model detection with capability-based detection
  src/praisonai-agents/praisonaiagents/agents/autoagents.py
  src/praisonai-agents/praisonaiagents/llm/__init__.py
  src/praisonai-agents/praisonaiagents/llm/llm.py
  src/praisonai-agents/praisonaiagents/llm/model_capabilities.py
Labels: Review effort 3/5

#817 fix: resolve SyntaxError in autoagents.py
  src/praisonai-agents/praisonaiagents/agents/autoagents.py
Labels: Review effort 4/5

#819 fix: enable tool calling for Gemini models
  src/praisonai-agents/praisonaiagents/agent/agent.py
  src/praisonai-agents/praisonaiagents/llm/llm.py
  src/praisonai/tests/unit/test_async_gemini_fix.py
  src/praisonai/tests/unit/test_gemini_tool_choice.py
  src/praisonai/tests/unit/test_tool_fix_documentation.md
  src/praisonai/tests/unit/test_tool_fix_example.py
  src/praisonai/tests/unit/test_tool_fix_improved.py
Labels: Review effort 3/5

#814 Add 10 New Grok4 Intelligent Agents Covering Diverse Domains
  examples/python/tools/exa-tool/grok4_intelligent_agents/grok_data_analysis_agent.py
  examples/python/tools/exa-tool/grok4_intelligent_agents/grok_deep_research_agent.py
  examples/python/tools/exa-tool/grok4_intelligent_agents/grok_health_fitness_agent.py
  examples/python/tools/exa-tool/grok4_intelligent_agents/grok_investment_advisor_agent.py
  examples/python/tools/exa-tool/grok4_intelligent_agents/grok_journalist_agent.py
  examples/python/tools/exa-tool/grok4_intelligent_agents/grok_medical_imaging_agent.py
  examples/python/tools/exa-tool/grok4_intelligent_agents/grok_music_generator_agent.py
  examples/python/tools/exa-tool/grok4_intelligent_agents/grok_personal_finance_agent.py
  examples/python/tools/exa-tool/grok4_intelligent_agents/grok_startup_trend_analysis_agent.py
  examples/python/tools/exa-tool/grok4_intelligent_agents/grok_travel_planning_agent.py
Labels: Review effort 2/5

#826 feat: Implement MCP HTTP Stream transport
  src/praisonai-agents/praisonaiagents/mcp/mcp.py
  src/praisonai-agents/praisonaiagents/mcp/mcp_http_stream.py
  src/praisonai-agents/praisonaiagents/mcp/mcp_sse.py
  src/praisonai-agents/pyproject.toml
  src/praisonai-agents/tests/mcp-http-stream-example.py
  src/praisonai-agents/tests/test_http_stream_basic.py
Labels: Review effort 4/5

#829 fix: add validation feedback to workflow retry logic
  example_validation_feedback.py
  review_validation_changes.py
  src/praisonai-agents/praisonaiagents/process/process.py
  src/praisonai-agents/praisonaiagents/task/task.py
  src/praisonai-agents/tests/test_validation_feedback.py
  test_validation_feedback.py
Labels: Review effort 3/5

#832 fix: sequential tool calling for non-streaming responses
  src/praisonai-agents/praisonaiagents/llm/llm.py
  src/praisonai-agents/test_sequential_tool_calling.py
Labels: Review effort 3/5

#836 fix: capture final response after tool execution in LLM
  src/praisonai-agents/praisonaiagents/llm/llm.py
Labels: Review effort 2/5
